# Generated by Django 5.1.4 on 2025-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_queue_address_alter_queue_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
